### ISSUE TITLE
Running setup.py install for shellphish-afl ... -Killed

### ISSUE THREAD

**Issue by ghost** [shellphish/shellphish-afl#10]
Collecting git+https://github.com/shellphish/shellphish-afl.git
  Cloning https://github.com/shellphish/shellphish-afl.git to /tmp/pip-h4g2IR-build
Installing collected packages: shellphish-afl
  Running setup.py install for shellphish-afl ... -Killed

I wanna install rex on my computer. I follow the link in https://github.com/shellphish/rex/issues/5, in the last step, it still report this error. I do the installation in docker angr. I repeat many times. the results are the same. right now , I don't how to do...., call for help

**Comment by zardus** [comment]
I don't have time to look into this at the moment, but I'd recommend that
you use the shellphish/mechaphish docker image, which already has all this
installed.

As a side note, angr is currently undergoing a pretty big refactor, and rex
hasn't yet been fully updated to it (not quite enough hackerpower), so
things may be broken.


On Aug 14, 2017 8:44 AM, "raycp" <notifications@github.com> wrote:

Collecting git+https://github.com/shellphish/shellphish-afl.git
Cloning https://github.com/shellphish/shellphish-afl.git to
/tmp/pip-h4g2IR-build
Installing collected packages: shellphish-afl
Running setup.py install for shellphish-afl ... -Killed

I wanna install rex on my computer. I follow the link in shellphish/rex#5
<https://github.com/shellphish/rex/issues/5>, in the last step, it still
report this error. I do the installation in docker angr. I repeat many
times. the results are the same. right now , I don't how to do...., call
for help

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/shellphish/shellphish-afl/issues/10>, or mute the thread

**Comment by ghost** [comment]
thx very much

**Comment by ghost** [comment]
one more question, I pulled shellphish/mechaphish this morning on my Mac OS, but the all the test script did't work?  isn't the this crs need run on the CGC cloud servers, it did't work on other system? @zardus

**Comment by zardus** [comment]
The components of the CRS (rex, patcherex, driller, etc) can run without being on the CGC cloud.

However, at the current moment, all three are broken due to recent refactors in angr. We're working on getting them fixed up but, as always, hackernpower is an issue.

**Comment by Kyle-Kyle** [comment]
I encountered the same problem and solved it.
The problem is the compilation process take too much memory you machine has. 
After changing max memory to 4G, this problem was resolved.

The underlying problems is sometimes 30 or more compilation processes are on going at the same time.
